database:
    driver: 'pdo_mysql'
    host: 'localhost'
    dbname: 'shop'
    port: '22'
    user: 'user'
    password : 'password'
    charset: utf8
    defaultTableOptions: { collate: utf8_general_ci }
