# duplicated
root: /shop/html/ # root_urlpath
admin_dir: admin/ # admin_route
tpl: /shop/html/user_data/packages/default/ # front_urlpath
admin_tpl: /shop/html/user_data/packages/admin/ # admin_urlpath
image_path: /shop/html/upload/save_image/ # image_save_urlpath

# base valiables
root_dir: /var/www/html/shop
root_urlpath: /shop/html
template_code: default

# routing
admin_route: admin
user_data_route: user_data

# public directory
public_path: /html
public_path_realdir: /var/www/html/shop/html

# realdir::image
image_save_realdir: /var/www/html/shop/html/upload/save_image
image_temp_realdir: /var/www/html/shop/html/upload/temp_image

# realdir::user_data
user_data_realdir: /var/www/html/shop/html/user_data

# realdir::block
block_default_realdir: /var/www/html/shop/src/Eccube/Resource/template/default/Block
block_realdir: /var/www/html/shop/app/template/default/Block

# realdir::template
template_default_realdir: /var/www/html/shop/src/Eccube/Resource/template/default
template_default_html_realdir: /var/www/html/shop/html/template/default
template_admin_realdir: /var/www/html/shop/src/Eccube/Resource/template/admin
template_admin_html_realdir: /var/www/html/shop/html/template/admin
template_realdir: /var/www/html/shop/app/template/default
template_html_realdir: /var/www/html/shop/html/template/default
template_temp_realdir: /var/www/html/shop/app/cache/eccube/template

# realdir::csv
csv_temp_realdir: /var/www/html/shop/app/cache/eccube/csv

# realdir:plugin
plugin_realdir: /var/www/html/shop/app/Plugin
plugin_temp_realdir: /var/www/html/shop/app/cache/plugin
plugin_html_realdir: /var/www/html/shop/html/plugin

# urlpath
admin_urlpath: /shop/html/template/admin
front_urlpath: /shop/html/template/default
image_save_urlpath: /shop/html/upload/save_image
image_temp_urlpath: /shop/html/upload/temp_image
user_data_urlpath: /shop/html/user_data
plugin_urlpath: /shop/html/plugin
